# Generated by Django 3.0.2 on 2020-03-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='start',
            new_name='starter',
        ),
    ]
